# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170813_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question_id',
        ),
        migrations.RemoveField(
            model_name='usersurvey',
            name='choice_id',
        ),
        migrations.RemoveField(
            model_name='usersurvey',
            name='question_id',
        ),
        migrations.RemoveField(
            model_name='usersurvey',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='UserSurvey',
        ),
    ]
