# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0002_auto_20170827_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='question_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='steps.Question'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='step_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='steps.Step'),
        ),
    ]
